pipeline:
  testing:
    image: node:8.6.0
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile
      - yarn run test
      - yarn run lint
