workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  frontend:
    image: node:8.3.0
    group: testing
    commands:
      - yarn install
      - ./node_modules/.bin/mocha

  backend:
    image: node:8.3.0
    group: testing
    commands:
      - echo "backend testing"
