workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  master:
    image: node:8.3.0
    commands:
      - echo master
    when:
      branch: master

  develop:
    image: node:8.3.0
    commands:
      - echo develop
    when:
      branch: develop
