workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  frontend:
    image: node:8.3.0
    group: testing
    commands:
      - yarn install
      - ./node_modules/.bin/mocha

  backend:
    image: node:8.3.0
    group: testing
    commands:
      - echo "backend testing"

  node1:
    image: node:8.3.0
    group: build
    commands:
      - sleep 5
      - echo "sleep 5"

  node2:
    image: node:8.3.0
    group: build
    commands:
      - sleep 10
      - echo "sleep 10"

  node3:
    image: node:8.3.0
    group: build
    commands:
      - sleep 15
      - echo "sleep 15"
